In [1]:
import numpy as np

In [3]:
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

In [11]:
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
print("Size:" + str(Z.size * Z.itemsize))

Size:80


In [17]:
Z = np.zeros(10)
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
A = np.arange(10,50)
A

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [19]:
A[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [21]:
B = np.arange(9).reshape(3,3)
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
C = np.nonzero([1,2,0,0,4,0])
C

(array([0, 1, 4]),)

In [23]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
D = np.random.random((3,3,3))
D

array([[[0.96015491, 0.98357597, 0.88933515],
        [0.54632642, 0.46262668, 0.49850911],
        [0.08063498, 0.64926336, 0.12261715]],

       [[0.39982993, 0.57712391, 0.64139369],
        [0.66607855, 0.07177959, 0.60009312],
        [0.52544101, 0.27719878, 0.5854278 ]],

       [[0.28219685, 0.43318398, 0.72689862],
        [0.28469424, 0.41086542, 0.63956459],
        [0.36758859, 0.66024887, 0.48201557]]])

In [29]:
E = np.random.random((10,10))
Min = E.min()
Max = E.max()

print("Min: " + str(Min))
print("Max: " + str(Max))

Min: 0.003951362679356474
Max: 0.9867078744555329


In [31]:
F = np.random.random(30)
F.mean()

np.float64(0.5514506706509066)

In [33]:
G = np.zeros((10,10))
G[1:-1,1:-1] = 1
G

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
H = np.zeros((5,5))
H = np.pad(H, pad_width=1, mode="constant", constant_values=1)
H

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [36]:
J = np.diag(np.arange(1,5), k=-1)
J

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [37]:
K = np.zeros((8,8))
K[1::2,::2] = 1
K[::2, 1::2] = 1
K

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [39]:
np.unravel_index(99,(6,7,8))

(np.int64(1), np.int64(5), np.int64(3))


In [40]:
A = np.random.random((4,3))
B = np.random.random((3,4))

print(A)
print(B)
print(A@B)

[[7.71480332e-02 6.95017606e-01 6.13349733e-01]
 [6.91270659e-01 2.01014854e-01 1.40804915e-01]
 [1.23549362e-02 4.37218534e-01 2.35554762e-04]
 [6.69671994e-01 7.60491851e-02 5.89219797e-02]]
[[0.47549122 0.91490438 0.05916806 0.63185903]
 [0.37125307 0.95816625 0.28245393 0.80844087]
 [0.04388998 0.74194585 0.76109929 0.79006035]]
[[0.32163054 1.19159778 0.6676952  1.09521062]
 [0.40950043 0.92952183 0.2048451  0.71053861]
 [0.16820373 0.4304064  0.12440439 0.36145801]
 [0.34924273 0.72927052 0.10594906 0.53117149]]


In [41]:
A.mean()
A.std()

print(f"Mean: " + str(A.mean()))
print(f"Std: " + str(A.std()))

Mean: 0.3060881653553856
Std: 0.27809415844569335


In [55]:
B = np.random.random((5,2))
C = B * 1000

D = np.random.random(2) * 1000

diff = C - D
print(diff)
euclidean_distance = np.sqrt(np.sum(diff**2, axis=-1))
print(euclidean_distance)

[[ -62.01023411 -117.33703695]
 [  29.78408805 -205.48742348]
 [ 607.7734166   191.97716386]
 [-287.79341372 -190.16548129]
 [-228.15136983  456.00746792]]
[132.71491768 207.63471075 637.37254206 344.94631359 509.89789012]


In [56]:
import numpy as np


data = np.array([[25, 40000, 85],
                 [45, 85000, 92],
                 [30, 52000, 78],
                 [50, 90000, 96]], dtype=float)

min = data.min(axis = 0)
max = data.max(axis = 0)

normalized = (data - min) / (max - min)
print(normalized)

[[0.         0.         0.38888889]
 [0.8        0.9        0.77777778]
 [0.2        0.24       0.        ]
 [1.         1.         1.        ]]


In [58]:
labels = [1, 0, 0, 2, 3, 0, 2]

max_labels = np.max(labels) + 1
I = np.eye(max_labels)

one_hot = I[labels]
print(one_hot)

[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]


***Why is NumPy faster than Python lists?***

Numpy is faster because it uses contigous array to store data which is easier and faster to setch and use, whereas Python uses pointer based array allocation where each data of array is squeezed into some part of memory and is connected through pointers.

***What is broadcasting?***

Broadcasting is when we give uneven arrays to perform operation and numpy takes care of it using a memory efficient strategy rather than blind copying of data again and again. There are 2 rules that are used for broadcasting.

* Arrays must be equal
* One of the dimension should be 1 and not any other



***When can broadcasting become dangerous?***

Dangers in broadcasting includes inefficient usage of memory when handling large high dimensional data, which causes memory to fill up easily. Making this inefficient, and a efficient way to process this kind of data would be to chunk the calculation parts to manageable parts that do not block memory.


***Explain reshaping without changing data.***

Reshaping produces a copy of the orignal array in the requested shape but does not change the original one, changing values in reshaped one does not affect the original.


***Difference between flatten() and ravel().***

* Flatten ==> Converts the given n-D array to 1-D array by making a copy of it in some memory face.

* Ravel ==> Converts a given n-D array to 1-D array by making a view of the original array